### ISSUE TITLE
Timezone file might fallback to excluded directory

### ISSUE THREAD

**Issue by shirok1** [taoky/traverse#22]
下面的配置在不显式指定 `--timezone-file` 时会试图列出 `/configs/`

```toml
[[mirrors]]
name = "clickhouse"
interval = 360
provider = "command"
upstream = "https://packages.clickhouse.com/"
command = "/opt/tunasync/script/tsumugu.sh"
[mirrors.env]
TUNASYNC_TSUMUGU_THREADS = "8"
TUNASYNC_TSUMUGU_PARSER = "denoflare-r2"
TUNASYNC_TSUMUGU_OPTIONS = "--apt-packages --yum-packages --ignore-nonexist"
#TUNASYNC_TSUMUGU_TIMEZONEFILE = "https://packages.clickhouse.com/deb/dists/stable/InRelease"
TUNASYNC_TSUMUGU_EXCLUDE = '''
--exclude ^/configs/
--exclude ^/repo-archive/
'''
```
